//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyChef.WebModules.ShoppingCart.Admin {
    
    
    public partial class OrderFulfillmentEditor {
        
        /// <summary>
        /// OrderFulfillmentAlaCarte_Edit1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HealthyChef.WebModules.ShoppingCart.Admin.UserControls.OrderFulfillmentAlaCarte_Edit OrderFulfillmentAlaCarte_Edit1;
        
        /// <summary>
        /// OrderFulfillmentProgram_Edit1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HealthyChef.WebModules.ShoppingCart.Admin.UserControls.OrderFulfillmentProgram_Edit OrderFulfillmentProgram_Edit1;
        
        /// <summary>
        /// OrderFulfillmentGiftCert_Edit1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HealthyChef.WebModules.ShoppingCart.Admin.UserControls.OrderFulfillmentGiftCert_Edit OrderFulfillmentGiftCert_Edit1;
    }
}
