#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BayshoreSolutions.WebModules.FormBuilder
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WebModulesCMS")]
	public partial class FormBuilderDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFormBuilder_Field(FormBuilder_Field instance);
    partial void UpdateFormBuilder_Field(FormBuilder_Field instance);
    partial void DeleteFormBuilder_Field(FormBuilder_Field instance);
    partial void InsertFormBuilder_Template_Field(FormBuilder_Template_Field instance);
    partial void UpdateFormBuilder_Template_Field(FormBuilder_Template_Field instance);
    partial void DeleteFormBuilder_Template_Field(FormBuilder_Template_Field instance);
    partial void InsertFormBuilder_FieldInput(FormBuilder_FieldInput instance);
    partial void UpdateFormBuilder_FieldInput(FormBuilder_FieldInput instance);
    partial void DeleteFormBuilder_FieldInput(FormBuilder_FieldInput instance);
    partial void InsertFormBuilder_Response(FormBuilder_Response instance);
    partial void UpdateFormBuilder_Response(FormBuilder_Response instance);
    partial void DeleteFormBuilder_Response(FormBuilder_Response instance);
    partial void InsertFormBuilder_Template(FormBuilder_Template instance);
    partial void UpdateFormBuilder_Template(FormBuilder_Template instance);
    partial void DeleteFormBuilder_Template(FormBuilder_Template instance);
    partial void InsertFormBuilder_ResponseReferrer(FormBuilder_ResponseReferrer instance);
    partial void UpdateFormBuilder_ResponseReferrer(FormBuilder_ResponseReferrer instance);
    partial void DeleteFormBuilder_ResponseReferrer(FormBuilder_ResponseReferrer instance);
    partial void InsertFormBuilder_Module(FormBuilder_Module instance);
    partial void UpdateFormBuilder_Module(FormBuilder_Module instance);
    partial void DeleteFormBuilder_Module(FormBuilder_Module instance);
    #endregion
		
		public FormBuilderDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["WebModules"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FormBuilderDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FormBuilderDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FormBuilderDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FormBuilderDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<FormBuilder_Field> FormBuilder_Fields
		{
			get
			{
				return this.GetTable<FormBuilder_Field>();
			}
		}
		
		public System.Data.Linq.Table<FormBuilder_Template_Field> FormBuilder_Template_Fields
		{
			get
			{
				return this.GetTable<FormBuilder_Template_Field>();
			}
		}
		
		public System.Data.Linq.Table<FormBuilder_FieldInput> FormBuilder_FieldInputs
		{
			get
			{
				return this.GetTable<FormBuilder_FieldInput>();
			}
		}
		
		public System.Data.Linq.Table<FormBuilder_Response> FormBuilder_Responses
		{
			get
			{
				return this.GetTable<FormBuilder_Response>();
			}
		}
		
		public System.Data.Linq.Table<FormBuilder_Template> FormBuilder_Templates
		{
			get
			{
				return this.GetTable<FormBuilder_Template>();
			}
		}
		
		public System.Data.Linq.Table<FormBuilder_ResponseReferrer> FormBuilder_ResponseReferrers
		{
			get
			{
				return this.GetTable<FormBuilder_ResponseReferrer>();
			}
		}
		
		public System.Data.Linq.Table<FormBuilder_Module> FormBuilder_Modules
		{
			get
			{
				return this.GetTable<FormBuilder_Module>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FormBuilder_Field_MovePosition")]
		public int FormBuilder_Field_MovePosition([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> direction)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, direction);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FormBuilder_Field_RebuildSortOrder")]
		public int FormBuilder_Field_RebuildSortOrder([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> moduleId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), moduleId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FormBuilder_FieldInput_GetByModuleId")]
		public ISingleResult<FormBuilder_FieldInput_GetByModuleIdResult> FormBuilder_FieldInput_GetByModuleId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> moduleId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> endDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), moduleId, startDate, endDate);
			return ((ISingleResult<FormBuilder_FieldInput_GetByModuleIdResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FormBuilder_Field")]
	public partial class FormBuilder_Field : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _ModuleId;
		
		private string _Name;
		
		private string _HelpText;
		
		private int _Type;
		
		private string _Options;
		
		private int _SortOrder;
		
		private System.Nullable<int> _Width;
		
		private bool _IsRequired;
		
		private EntitySet<FormBuilder_FieldInput> _FormBuilder_FieldInputs;
		
		private EntityRef<FormBuilder_Module> _FormBuilder_Module;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnModuleIdChanging(int value);
    partial void OnModuleIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnHelpTextChanging(string value);
    partial void OnHelpTextChanged();
    partial void OnTypeChanging(int value);
    partial void OnTypeChanged();
    partial void OnOptionsChanging(string value);
    partial void OnOptionsChanged();
    partial void OnSortOrderChanging(int value);
    partial void OnSortOrderChanged();
    partial void OnWidthChanging(System.Nullable<int> value);
    partial void OnWidthChanged();
    partial void OnIsRequiredChanging(bool value);
    partial void OnIsRequiredChanged();
    #endregion
		
		public FormBuilder_Field()
		{
			this._FormBuilder_FieldInputs = new EntitySet<FormBuilder_FieldInput>(new Action<FormBuilder_FieldInput>(this.attach_FormBuilder_FieldInputs), new Action<FormBuilder_FieldInput>(this.detach_FormBuilder_FieldInputs));
			this._FormBuilder_Module = default(EntityRef<FormBuilder_Module>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleId", DbType="Int NOT NULL")]
		public int ModuleId
		{
			get
			{
				return this._ModuleId;
			}
			set
			{
				if ((this._ModuleId != value))
				{
					if (this._FormBuilder_Module.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnModuleIdChanging(value);
					this.SendPropertyChanging();
					this._ModuleId = value;
					this.SendPropertyChanged("ModuleId");
					this.OnModuleIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HelpText", DbType="NVarChar(512)")]
		public string HelpText
		{
			get
			{
				return this._HelpText;
			}
			set
			{
				if ((this._HelpText != value))
				{
					this.OnHelpTextChanging(value);
					this.SendPropertyChanging();
					this._HelpText = value;
					this.SendPropertyChanged("HelpText");
					this.OnHelpTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int NOT NULL")]
		public int Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Options", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Options
		{
			get
			{
				return this._Options;
			}
			set
			{
				if ((this._Options != value))
				{
					this.OnOptionsChanging(value);
					this.SendPropertyChanging();
					this._Options = value;
					this.SendPropertyChanged("Options");
					this.OnOptionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int NOT NULL")]
		public int SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Width", DbType="Int")]
		public System.Nullable<int> Width
		{
			get
			{
				return this._Width;
			}
			set
			{
				if ((this._Width != value))
				{
					this.OnWidthChanging(value);
					this.SendPropertyChanging();
					this._Width = value;
					this.SendPropertyChanged("Width");
					this.OnWidthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRequired", DbType="Bit NOT NULL")]
		public bool IsRequired
		{
			get
			{
				return this._IsRequired;
			}
			set
			{
				if ((this._IsRequired != value))
				{
					this.OnIsRequiredChanging(value);
					this.SendPropertyChanging();
					this._IsRequired = value;
					this.SendPropertyChanged("IsRequired");
					this.OnIsRequiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FormBuilder_Field_FormBuilder_FieldInput", Storage="_FormBuilder_FieldInputs", ThisKey="Id", OtherKey="FieldId")]
		public EntitySet<FormBuilder_FieldInput> FormBuilder_FieldInputs
		{
			get
			{
				return this._FormBuilder_FieldInputs;
			}
			set
			{
				this._FormBuilder_FieldInputs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FormBuilder_Module_FormBuilder_Field", Storage="_FormBuilder_Module", ThisKey="ModuleId", OtherKey="ModuleId", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public FormBuilder_Module FormBuilder_Module
		{
			get
			{
				return this._FormBuilder_Module.Entity;
			}
			set
			{
				FormBuilder_Module previousValue = this._FormBuilder_Module.Entity;
				if (((previousValue != value) 
							|| (this._FormBuilder_Module.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FormBuilder_Module.Entity = null;
						previousValue.FormBuilder_Fields.Remove(this);
					}
					this._FormBuilder_Module.Entity = value;
					if ((value != null))
					{
						value.FormBuilder_Fields.Add(this);
						this._ModuleId = value.ModuleId;
					}
					else
					{
						this._ModuleId = default(int);
					}
					this.SendPropertyChanged("FormBuilder_Module");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FormBuilder_FieldInputs(FormBuilder_FieldInput entity)
		{
			this.SendPropertyChanging();
			entity.FormBuilder_Field = this;
		}
		
		private void detach_FormBuilder_FieldInputs(FormBuilder_FieldInput entity)
		{
			this.SendPropertyChanging();
			entity.FormBuilder_Field = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FormBuilder_Template_Field")]
	public partial class FormBuilder_Template_Field : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _TemplateId;
		
		private string _Name;
		
		private string _HelpText;
		
		private int _Type;
		
		private string _Options;
		
		private int _SortOrder;
		
		private System.Nullable<int> _Width;
		
		private bool _IsRequired;
		
		private EntityRef<FormBuilder_Template> _FormBuilder_Template;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTemplateIdChanging(int value);
    partial void OnTemplateIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnHelpTextChanging(string value);
    partial void OnHelpTextChanged();
    partial void OnTypeChanging(int value);
    partial void OnTypeChanged();
    partial void OnOptionsChanging(string value);
    partial void OnOptionsChanged();
    partial void OnSortOrderChanging(int value);
    partial void OnSortOrderChanged();
    partial void OnWidthChanging(System.Nullable<int> value);
    partial void OnWidthChanged();
    partial void OnIsRequiredChanging(bool value);
    partial void OnIsRequiredChanged();
    #endregion
		
		public FormBuilder_Template_Field()
		{
			this._FormBuilder_Template = default(EntityRef<FormBuilder_Template>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateId", DbType="Int NOT NULL")]
		public int TemplateId
		{
			get
			{
				return this._TemplateId;
			}
			set
			{
				if ((this._TemplateId != value))
				{
					if (this._FormBuilder_Template.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTemplateIdChanging(value);
					this.SendPropertyChanging();
					this._TemplateId = value;
					this.SendPropertyChanged("TemplateId");
					this.OnTemplateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HelpText", DbType="NVarChar(512)")]
		public string HelpText
		{
			get
			{
				return this._HelpText;
			}
			set
			{
				if ((this._HelpText != value))
				{
					this.OnHelpTextChanging(value);
					this.SendPropertyChanging();
					this._HelpText = value;
					this.SendPropertyChanged("HelpText");
					this.OnHelpTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int NOT NULL")]
		public int Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Options", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Options
		{
			get
			{
				return this._Options;
			}
			set
			{
				if ((this._Options != value))
				{
					this.OnOptionsChanging(value);
					this.SendPropertyChanging();
					this._Options = value;
					this.SendPropertyChanged("Options");
					this.OnOptionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int NOT NULL")]
		public int SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Width", DbType="Int")]
		public System.Nullable<int> Width
		{
			get
			{
				return this._Width;
			}
			set
			{
				if ((this._Width != value))
				{
					this.OnWidthChanging(value);
					this.SendPropertyChanging();
					this._Width = value;
					this.SendPropertyChanged("Width");
					this.OnWidthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRequired", DbType="Bit NOT NULL")]
		public bool IsRequired
		{
			get
			{
				return this._IsRequired;
			}
			set
			{
				if ((this._IsRequired != value))
				{
					this.OnIsRequiredChanging(value);
					this.SendPropertyChanging();
					this._IsRequired = value;
					this.SendPropertyChanged("IsRequired");
					this.OnIsRequiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FormBuilder_Template_FormBuilder_Template_Field", Storage="_FormBuilder_Template", ThisKey="TemplateId", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public FormBuilder_Template FormBuilder_Template
		{
			get
			{
				return this._FormBuilder_Template.Entity;
			}
			set
			{
				FormBuilder_Template previousValue = this._FormBuilder_Template.Entity;
				if (((previousValue != value) 
							|| (this._FormBuilder_Template.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FormBuilder_Template.Entity = null;
						previousValue.FormBuilder_Template_Fields.Remove(this);
					}
					this._FormBuilder_Template.Entity = value;
					if ((value != null))
					{
						value.FormBuilder_Template_Fields.Add(this);
						this._TemplateId = value.Id;
					}
					else
					{
						this._TemplateId = default(int);
					}
					this.SendPropertyChanged("FormBuilder_Template");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FormBuilder_FieldInput")]
	public partial class FormBuilder_FieldInput : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _ResponseId;
		
		private int _FieldId;
		
		private string _InputValue;
		
		private EntityRef<FormBuilder_Field> _FormBuilder_Field;
		
		private EntityRef<FormBuilder_Response> _FormBuilder_Response;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnResponseIdChanging(int value);
    partial void OnResponseIdChanged();
    partial void OnFieldIdChanging(int value);
    partial void OnFieldIdChanged();
    partial void OnInputValueChanging(string value);
    partial void OnInputValueChanged();
    #endregion
		
		public FormBuilder_FieldInput()
		{
			this._FormBuilder_Field = default(EntityRef<FormBuilder_Field>);
			this._FormBuilder_Response = default(EntityRef<FormBuilder_Response>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResponseId", DbType="Int NOT NULL")]
		public int ResponseId
		{
			get
			{
				return this._ResponseId;
			}
			set
			{
				if ((this._ResponseId != value))
				{
					if (this._FormBuilder_Response.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnResponseIdChanging(value);
					this.SendPropertyChanging();
					this._ResponseId = value;
					this.SendPropertyChanged("ResponseId");
					this.OnResponseIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FieldId", DbType="Int NOT NULL")]
		public int FieldId
		{
			get
			{
				return this._FieldId;
			}
			set
			{
				if ((this._FieldId != value))
				{
					if (this._FormBuilder_Field.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFieldIdChanging(value);
					this.SendPropertyChanging();
					this._FieldId = value;
					this.SendPropertyChanged("FieldId");
					this.OnFieldIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InputValue", DbType="NVarChar(4000)")]
		public string InputValue
		{
			get
			{
				return this._InputValue;
			}
			set
			{
				if ((this._InputValue != value))
				{
					this.OnInputValueChanging(value);
					this.SendPropertyChanging();
					this._InputValue = value;
					this.SendPropertyChanged("InputValue");
					this.OnInputValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FormBuilder_Field_FormBuilder_FieldInput", Storage="_FormBuilder_Field", ThisKey="FieldId", OtherKey="Id", IsForeignKey=true)]
		public FormBuilder_Field FormBuilder_Field
		{
			get
			{
				return this._FormBuilder_Field.Entity;
			}
			set
			{
				FormBuilder_Field previousValue = this._FormBuilder_Field.Entity;
				if (((previousValue != value) 
							|| (this._FormBuilder_Field.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FormBuilder_Field.Entity = null;
						previousValue.FormBuilder_FieldInputs.Remove(this);
					}
					this._FormBuilder_Field.Entity = value;
					if ((value != null))
					{
						value.FormBuilder_FieldInputs.Add(this);
						this._FieldId = value.Id;
					}
					else
					{
						this._FieldId = default(int);
					}
					this.SendPropertyChanged("FormBuilder_Field");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FormBuilder_Response_FormBuilder_FieldInput", Storage="_FormBuilder_Response", ThisKey="ResponseId", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public FormBuilder_Response FormBuilder_Response
		{
			get
			{
				return this._FormBuilder_Response.Entity;
			}
			set
			{
				FormBuilder_Response previousValue = this._FormBuilder_Response.Entity;
				if (((previousValue != value) 
							|| (this._FormBuilder_Response.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FormBuilder_Response.Entity = null;
						previousValue.FormBuilder_FieldInputs.Remove(this);
					}
					this._FormBuilder_Response.Entity = value;
					if ((value != null))
					{
						value.FormBuilder_FieldInputs.Add(this);
						this._ResponseId = value.Id;
					}
					else
					{
						this._ResponseId = default(int);
					}
					this.SendPropertyChanged("FormBuilder_Response");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FormBuilder_Response")]
	public partial class FormBuilder_Response : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _ModuleId;
		
		private string _IPAddress;
		
		private string _CreatedBy;
		
		private System.DateTime _CreatedOn;
		
		private bool _IsComplete;
		
		private EntitySet<FormBuilder_FieldInput> _FormBuilder_FieldInputs;
		
		private EntitySet<FormBuilder_ResponseReferrer> _FormBuilder_ResponseReferrers;
		
		private EntityRef<FormBuilder_Module> _FormBuilder_Module;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnModuleIdChanging(int value);
    partial void OnModuleIdChanged();
    partial void OnIPAddressChanging(string value);
    partial void OnIPAddressChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnCreatedOnChanging(System.DateTime value);
    partial void OnCreatedOnChanged();
    partial void OnIsCompleteChanging(bool value);
    partial void OnIsCompleteChanged();
    #endregion
		
		public FormBuilder_Response()
		{
			this._FormBuilder_FieldInputs = new EntitySet<FormBuilder_FieldInput>(new Action<FormBuilder_FieldInput>(this.attach_FormBuilder_FieldInputs), new Action<FormBuilder_FieldInput>(this.detach_FormBuilder_FieldInputs));
			this._FormBuilder_ResponseReferrers = new EntitySet<FormBuilder_ResponseReferrer>(new Action<FormBuilder_ResponseReferrer>(this.attach_FormBuilder_ResponseReferrers), new Action<FormBuilder_ResponseReferrer>(this.detach_FormBuilder_ResponseReferrers));
			this._FormBuilder_Module = default(EntityRef<FormBuilder_Module>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleId", DbType="Int NOT NULL")]
		public int ModuleId
		{
			get
			{
				return this._ModuleId;
			}
			set
			{
				if ((this._ModuleId != value))
				{
					if (this._FormBuilder_Module.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnModuleIdChanging(value);
					this.SendPropertyChanging();
					this._ModuleId = value;
					this.SendPropertyChanged("ModuleId");
					this.OnModuleIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPAddress", DbType="VarChar(15)")]
		public string IPAddress
		{
			get
			{
				return this._IPAddress;
			}
			set
			{
				if ((this._IPAddress != value))
				{
					this.OnIPAddressChanging(value);
					this.SendPropertyChanging();
					this._IPAddress = value;
					this.SendPropertyChanged("IPAddress");
					this.OnIPAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(256)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsComplete", DbType="Bit NOT NULL")]
		public bool IsComplete
		{
			get
			{
				return this._IsComplete;
			}
			set
			{
				if ((this._IsComplete != value))
				{
					this.OnIsCompleteChanging(value);
					this.SendPropertyChanging();
					this._IsComplete = value;
					this.SendPropertyChanged("IsComplete");
					this.OnIsCompleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FormBuilder_Response_FormBuilder_FieldInput", Storage="_FormBuilder_FieldInputs", ThisKey="Id", OtherKey="ResponseId")]
		public EntitySet<FormBuilder_FieldInput> FormBuilder_FieldInputs
		{
			get
			{
				return this._FormBuilder_FieldInputs;
			}
			set
			{
				this._FormBuilder_FieldInputs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FormBuilder_Response_FormBuilder_ResponseReferrer", Storage="_FormBuilder_ResponseReferrers", ThisKey="Id", OtherKey="ResponseId")]
		public EntitySet<FormBuilder_ResponseReferrer> FormBuilder_ResponseReferrers
		{
			get
			{
				return this._FormBuilder_ResponseReferrers;
			}
			set
			{
				this._FormBuilder_ResponseReferrers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FormBuilder_Module_FormBuilder_Response", Storage="_FormBuilder_Module", ThisKey="ModuleId", OtherKey="ModuleId", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public FormBuilder_Module FormBuilder_Module
		{
			get
			{
				return this._FormBuilder_Module.Entity;
			}
			set
			{
				FormBuilder_Module previousValue = this._FormBuilder_Module.Entity;
				if (((previousValue != value) 
							|| (this._FormBuilder_Module.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FormBuilder_Module.Entity = null;
						previousValue.FormBuilder_Responses.Remove(this);
					}
					this._FormBuilder_Module.Entity = value;
					if ((value != null))
					{
						value.FormBuilder_Responses.Add(this);
						this._ModuleId = value.ModuleId;
					}
					else
					{
						this._ModuleId = default(int);
					}
					this.SendPropertyChanged("FormBuilder_Module");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FormBuilder_FieldInputs(FormBuilder_FieldInput entity)
		{
			this.SendPropertyChanging();
			entity.FormBuilder_Response = this;
		}
		
		private void detach_FormBuilder_FieldInputs(FormBuilder_FieldInput entity)
		{
			this.SendPropertyChanging();
			entity.FormBuilder_Response = null;
		}
		
		private void attach_FormBuilder_ResponseReferrers(FormBuilder_ResponseReferrer entity)
		{
			this.SendPropertyChanging();
			entity.FormBuilder_Response = this;
		}
		
		private void detach_FormBuilder_ResponseReferrers(FormBuilder_ResponseReferrer entity)
		{
			this.SendPropertyChanging();
			entity.FormBuilder_Response = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FormBuilder_Template")]
	public partial class FormBuilder_Template : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private EntitySet<FormBuilder_Template_Field> _FormBuilder_Template_Fields;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public FormBuilder_Template()
		{
			this._FormBuilder_Template_Fields = new EntitySet<FormBuilder_Template_Field>(new Action<FormBuilder_Template_Field>(this.attach_FormBuilder_Template_Fields), new Action<FormBuilder_Template_Field>(this.detach_FormBuilder_Template_Fields));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FormBuilder_Template_FormBuilder_Template_Field", Storage="_FormBuilder_Template_Fields", ThisKey="Id", OtherKey="TemplateId")]
		public EntitySet<FormBuilder_Template_Field> FormBuilder_Template_Fields
		{
			get
			{
				return this._FormBuilder_Template_Fields;
			}
			set
			{
				this._FormBuilder_Template_Fields.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FormBuilder_Template_Fields(FormBuilder_Template_Field entity)
		{
			this.SendPropertyChanging();
			entity.FormBuilder_Template = this;
		}
		
		private void detach_FormBuilder_Template_Fields(FormBuilder_Template_Field entity)
		{
			this.SendPropertyChanging();
			entity.FormBuilder_Template = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FormBuilder_ResponseReferrer")]
	public partial class FormBuilder_ResponseReferrer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _ResponseId;
		
		private string _domain;
		
		private string _query;
		
		private string _referringUrl;
		
		private string _landingUrl;
		
		private EntityRef<FormBuilder_Response> _FormBuilder_Response;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnResponseIdChanging(int value);
    partial void OnResponseIdChanged();
    partial void OndomainChanging(string value);
    partial void OndomainChanged();
    partial void OnqueryChanging(string value);
    partial void OnqueryChanged();
    partial void OnreferringUrlChanging(string value);
    partial void OnreferringUrlChanged();
    partial void OnlandingUrlChanging(string value);
    partial void OnlandingUrlChanged();
    #endregion
		
		public FormBuilder_ResponseReferrer()
		{
			this._FormBuilder_Response = default(EntityRef<FormBuilder_Response>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResponseId", DbType="Int NOT NULL")]
		public int ResponseId
		{
			get
			{
				return this._ResponseId;
			}
			set
			{
				if ((this._ResponseId != value))
				{
					if (this._FormBuilder_Response.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnResponseIdChanging(value);
					this.SendPropertyChanging();
					this._ResponseId = value;
					this.SendPropertyChanged("ResponseId");
					this.OnResponseIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domain", DbType="VarChar(255)")]
		public string domain
		{
			get
			{
				return this._domain;
			}
			set
			{
				if ((this._domain != value))
				{
					this.OndomainChanging(value);
					this.SendPropertyChanging();
					this._domain = value;
					this.SendPropertyChanged("domain");
					this.OndomainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_query", DbType="VarChar(255)")]
		public string query
		{
			get
			{
				return this._query;
			}
			set
			{
				if ((this._query != value))
				{
					this.OnqueryChanging(value);
					this.SendPropertyChanging();
					this._query = value;
					this.SendPropertyChanged("query");
					this.OnqueryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referringUrl", DbType="VarChar(1024)")]
		public string referringUrl
		{
			get
			{
				return this._referringUrl;
			}
			set
			{
				if ((this._referringUrl != value))
				{
					this.OnreferringUrlChanging(value);
					this.SendPropertyChanging();
					this._referringUrl = value;
					this.SendPropertyChanged("referringUrl");
					this.OnreferringUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_landingUrl", DbType="VarChar(1024)")]
		public string landingUrl
		{
			get
			{
				return this._landingUrl;
			}
			set
			{
				if ((this._landingUrl != value))
				{
					this.OnlandingUrlChanging(value);
					this.SendPropertyChanging();
					this._landingUrl = value;
					this.SendPropertyChanged("landingUrl");
					this.OnlandingUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FormBuilder_Response_FormBuilder_ResponseReferrer", Storage="_FormBuilder_Response", ThisKey="ResponseId", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public FormBuilder_Response FormBuilder_Response
		{
			get
			{
				return this._FormBuilder_Response.Entity;
			}
			set
			{
				FormBuilder_Response previousValue = this._FormBuilder_Response.Entity;
				if (((previousValue != value) 
							|| (this._FormBuilder_Response.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FormBuilder_Response.Entity = null;
						previousValue.FormBuilder_ResponseReferrers.Remove(this);
					}
					this._FormBuilder_Response.Entity = value;
					if ((value != null))
					{
						value.FormBuilder_ResponseReferrers.Add(this);
						this._ResponseId = value.Id;
					}
					else
					{
						this._ResponseId = default(int);
					}
					this.SendPropertyChanged("FormBuilder_Response");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FormBuilder_Module")]
	public partial class FormBuilder_Module : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ModuleId;
		
		private string _NotifyEmail;
		
		private System.Nullable<int> _ConfirmationPageId;
		
		private string _StyleName;
		
		private string _SubmitButtonText;
		
		private bool _Ack_Enabled;
		
		private string _Ack_FromEmailAddress;
		
		private string _Ack_EmailAddressFieldLabel;
		
		private string _Ack_Subject;
		
		private string _Ack_Body;
		
		private EntitySet<FormBuilder_Field> _FormBuilder_Fields;
		
		private EntitySet<FormBuilder_Response> _FormBuilder_Responses;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnModuleIdChanging(int value);
    partial void OnModuleIdChanged();
    partial void OnNotifyEmailChanging(string value);
    partial void OnNotifyEmailChanged();
    partial void OnConfirmationPageIdChanging(System.Nullable<int> value);
    partial void OnConfirmationPageIdChanged();
    partial void OnStyleNameChanging(string value);
    partial void OnStyleNameChanged();
    partial void OnSubmitButtonTextChanging(string value);
    partial void OnSubmitButtonTextChanged();
    partial void OnAck_EnabledChanging(bool value);
    partial void OnAck_EnabledChanged();
    partial void OnAck_FromEmailAddressChanging(string value);
    partial void OnAck_FromEmailAddressChanged();
    partial void OnAck_EmailAddressFieldLabelChanging(string value);
    partial void OnAck_EmailAddressFieldLabelChanged();
    partial void OnAck_SubjectChanging(string value);
    partial void OnAck_SubjectChanged();
    partial void OnAck_BodyChanging(string value);
    partial void OnAck_BodyChanged();
    #endregion
		
		public FormBuilder_Module()
		{
			this._FormBuilder_Fields = new EntitySet<FormBuilder_Field>(new Action<FormBuilder_Field>(this.attach_FormBuilder_Fields), new Action<FormBuilder_Field>(this.detach_FormBuilder_Fields));
			this._FormBuilder_Responses = new EntitySet<FormBuilder_Response>(new Action<FormBuilder_Response>(this.attach_FormBuilder_Responses), new Action<FormBuilder_Response>(this.detach_FormBuilder_Responses));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ModuleId
		{
			get
			{
				return this._ModuleId;
			}
			set
			{
				if ((this._ModuleId != value))
				{
					this.OnModuleIdChanging(value);
					this.SendPropertyChanging();
					this._ModuleId = value;
					this.SendPropertyChanged("ModuleId");
					this.OnModuleIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotifyEmail", DbType="NVarChar(250)")]
		public string NotifyEmail
		{
			get
			{
				return this._NotifyEmail;
			}
			set
			{
				if ((this._NotifyEmail != value))
				{
					this.OnNotifyEmailChanging(value);
					this.SendPropertyChanging();
					this._NotifyEmail = value;
					this.SendPropertyChanged("NotifyEmail");
					this.OnNotifyEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmationPageId", DbType="Int")]
		public System.Nullable<int> ConfirmationPageId
		{
			get
			{
				return this._ConfirmationPageId;
			}
			set
			{
				if ((this._ConfirmationPageId != value))
				{
					this.OnConfirmationPageIdChanging(value);
					this.SendPropertyChanging();
					this._ConfirmationPageId = value;
					this.SendPropertyChanged("ConfirmationPageId");
					this.OnConfirmationPageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleName", DbType="NVarChar(50)")]
		public string StyleName
		{
			get
			{
				return this._StyleName;
			}
			set
			{
				if ((this._StyleName != value))
				{
					this.OnStyleNameChanging(value);
					this.SendPropertyChanging();
					this._StyleName = value;
					this.SendPropertyChanged("StyleName");
					this.OnStyleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmitButtonText", DbType="NVarChar(50)")]
		public string SubmitButtonText
		{
			get
			{
				return this._SubmitButtonText;
			}
			set
			{
				if ((this._SubmitButtonText != value))
				{
					this.OnSubmitButtonTextChanging(value);
					this.SendPropertyChanging();
					this._SubmitButtonText = value;
					this.SendPropertyChanged("SubmitButtonText");
					this.OnSubmitButtonTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ack_Enabled", DbType="Bit NOT NULL")]
		public bool Ack_Enabled
		{
			get
			{
				return this._Ack_Enabled;
			}
			set
			{
				if ((this._Ack_Enabled != value))
				{
					this.OnAck_EnabledChanging(value);
					this.SendPropertyChanging();
					this._Ack_Enabled = value;
					this.SendPropertyChanged("Ack_Enabled");
					this.OnAck_EnabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ack_FromEmailAddress", DbType="NVarChar(256)")]
		public string Ack_FromEmailAddress
		{
			get
			{
				return this._Ack_FromEmailAddress;
			}
			set
			{
				if ((this._Ack_FromEmailAddress != value))
				{
					this.OnAck_FromEmailAddressChanging(value);
					this.SendPropertyChanging();
					this._Ack_FromEmailAddress = value;
					this.SendPropertyChanged("Ack_FromEmailAddress");
					this.OnAck_FromEmailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ack_EmailAddressFieldLabel", DbType="NVarChar(256)")]
		public string Ack_EmailAddressFieldLabel
		{
			get
			{
				return this._Ack_EmailAddressFieldLabel;
			}
			set
			{
				if ((this._Ack_EmailAddressFieldLabel != value))
				{
					this.OnAck_EmailAddressFieldLabelChanging(value);
					this.SendPropertyChanging();
					this._Ack_EmailAddressFieldLabel = value;
					this.SendPropertyChanged("Ack_EmailAddressFieldLabel");
					this.OnAck_EmailAddressFieldLabelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ack_Subject", DbType="NVarChar(256)")]
		public string Ack_Subject
		{
			get
			{
				return this._Ack_Subject;
			}
			set
			{
				if ((this._Ack_Subject != value))
				{
					this.OnAck_SubjectChanging(value);
					this.SendPropertyChanging();
					this._Ack_Subject = value;
					this.SendPropertyChanged("Ack_Subject");
					this.OnAck_SubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ack_Body", DbType="NVarChar(4000)")]
		public string Ack_Body
		{
			get
			{
				return this._Ack_Body;
			}
			set
			{
				if ((this._Ack_Body != value))
				{
					this.OnAck_BodyChanging(value);
					this.SendPropertyChanging();
					this._Ack_Body = value;
					this.SendPropertyChanged("Ack_Body");
					this.OnAck_BodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FormBuilder_Module_FormBuilder_Field", Storage="_FormBuilder_Fields", ThisKey="ModuleId", OtherKey="ModuleId")]
		public EntitySet<FormBuilder_Field> FormBuilder_Fields
		{
			get
			{
				return this._FormBuilder_Fields;
			}
			set
			{
				this._FormBuilder_Fields.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FormBuilder_Module_FormBuilder_Response", Storage="_FormBuilder_Responses", ThisKey="ModuleId", OtherKey="ModuleId")]
		public EntitySet<FormBuilder_Response> FormBuilder_Responses
		{
			get
			{
				return this._FormBuilder_Responses;
			}
			set
			{
				this._FormBuilder_Responses.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FormBuilder_Fields(FormBuilder_Field entity)
		{
			this.SendPropertyChanging();
			entity.FormBuilder_Module = this;
		}
		
		private void detach_FormBuilder_Fields(FormBuilder_Field entity)
		{
			this.SendPropertyChanging();
			entity.FormBuilder_Module = null;
		}
		
		private void attach_FormBuilder_Responses(FormBuilder_Response entity)
		{
			this.SendPropertyChanging();
			entity.FormBuilder_Module = this;
		}
		
		private void detach_FormBuilder_Responses(FormBuilder_Response entity)
		{
			this.SendPropertyChanging();
			entity.FormBuilder_Module = null;
		}
	}
	
	public partial class FormBuilder_FieldInput_GetByModuleIdResult
	{
		
		private int _Id;
		
		private int _ResponseId;
		
		private int _FieldId;
		
		private string _InputValue;
		
		public FormBuilder_FieldInput_GetByModuleIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResponseId", DbType="Int NOT NULL")]
		public int ResponseId
		{
			get
			{
				return this._ResponseId;
			}
			set
			{
				if ((this._ResponseId != value))
				{
					this._ResponseId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FieldId", DbType="Int NOT NULL")]
		public int FieldId
		{
			get
			{
				return this._FieldId;
			}
			set
			{
				if ((this._FieldId != value))
				{
					this._FieldId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InputValue", DbType="NVarChar(4000)")]
		public string InputValue
		{
			get
			{
				return this._InputValue;
			}
			set
			{
				if ((this._InputValue != value))
				{
					this._InputValue = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
