//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RssToolkit.Rss;
using System;
using System.Collections.Generic;
using System.Xml;
using System.Xml.Serialization;


namespace BayshoreSolutions.WebModules.MasterDetail.Rss
{

    [System.Serializable()]
    [System.Xml.Serialization.XmlRoot("rss")]
    public class MasterDetailRss : RssToolkit.Rss.RssDocumentBase
    {

        private string _version;

        private MasterDetailChannel _channel;

        [XmlAttribute("version")]
        public new string Version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }

        [XmlElement("channel")]
        public new MasterDetailChannel Channel
        {
            get
            {
                return _channel;
            }
            set
            {
                _channel = value;
            }
        }

        public static MasterDetailRss Load(System.Uri url)
        {
            if ((url == null))
            {
                throw new System.ArgumentNullException();
            }
            MasterDetailRss doc;
            doc = RssDocumentBase.Load<MasterDetailRss>(url);
            return doc;
        }

        public static MasterDetailRss Load(System.Xml.XmlTextReader reader)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException();
            }
            MasterDetailRss doc;
            doc = RssDocumentBase.Load<MasterDetailRss>(reader);
            return doc;
        }

        public static MasterDetailRss Load(string xml)
        {
            if (String.IsNullOrEmpty(xml))
            {
                throw new System.ArgumentNullException();
            }
            MasterDetailRss doc;
            doc = RssDocumentBase.Load<MasterDetailRss>(xml);
            return doc;
        }

        public override string ToXml(RssToolkit.Rss.DocumentType outputType)
        {
            return RssDocumentBase.ToXml<MasterDetailRss>(outputType, this);
        }

        public virtual System.Data.DataSet ToDataSet()
        {
            return RssXmlHelper.ToDataSet(ToXml(DocumentType.Rss));
        }
    }

    public class MasterDetailChannel
    {

        private string _title;

        private string _link;

        private string _description;

        private string _ttl;

        private string _name;

        private string _user;

        private string _image;

        private List<MasterDetailRssItem> _items;

        [XmlElement("title")]
        public string Title
        {
            get
            {
                return _title;
            }
            set
            {
                _title = value;
            }
        }

        [XmlElement("link")]
        public string Link
        {
            get
            {
                return _link;
            }
            set
            {
                _link = value;
            }
        }

        [XmlElement("description")]
        public string Description
        {
            get
            {
                return _description;
            }
            set
            {
                _description = value;
            }
        }

        [XmlElement("ttl")]
        public string Ttl
        {
            get
            {
                return _ttl;
            }
            set
            {
                _ttl = value;
            }
        }

        [XmlElement("name")]
        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }

        [XmlElement("user")]
        public string User
        {
            get
            {
                return _user;
            }
            set
            {
                _user = value;
            }
        }

        [XmlElement("image")]
        public string Image
        {
            get
            {
                return _image;
            }
            set
            {
                _image = value;
            }
        }

        [XmlElement("item")]
        public List<MasterDetailRssItem> Items
        {
            get
            {
                return _items;
            }
            set
            {
                _items = value;
            }
        }
    }

    public class MasterDetailRssItem
    {

        private string _title;

        private string _description;

        private string _category;

        private string _pubDate;

        private string _link;

        [XmlElement("title")]
        public string Title
        {
            get
            {
                return _title;
            }
            set
            {
                _title = value;
            }
        }

        [XmlElement("description")]
        public string Description
        {
            get
            {
                return _description;
            }
            set
            {
                _description = value;
            }
        }

        [XmlElement("category")]
        public string Category
        {
            get
            {
                return _category;
            }
            set
            {
                _category = value;
            }
        }

        [XmlElement("pubDate")]
        public string PubDate
        {
            get
            {
                return _pubDate;
            }
            set
            {
                _pubDate = value;
            }
        }

        [XmlElement("link")]
        public string Link
        {
            get
            {
                return _link;
            }
            set
            {
                _link = value;
            }
        }
    }

    public class MasterDetailHttpHandlerBase : RssToolkit.Rss.RssHttpHandlerBase<MasterDetailRss>
    {
    }

}